### ISSUE TITLE
case-insensitive

### ISSUE THREAD

**Issue by 91wangmeng** [Shinao/Wox.Plugins#1]
the vlaue case-insensitive

**Comment by Shinao** [comment]
Yes the search value is on purpose case insensitive, it makes sense to me.
For example if your search on your browser, it's also case insensitive, seems to be the default everywhere.

If you really want a case sensitive version you can remove the LowerCase() calls in Database.cs and Need.cs.

**Comment by novmikvis** [comment]
It would be **extremly** nice to have an option for case sensitivity. For example checkbox in Wox settings menu. Or in some more user friendly way, other than editing source code and rebuilding dlls manually.

Case sensetivity is useful for example, if I want to set up shorcut for image hosted on imgur. It would be impossible to do that, because imgur links are case sensetive

You will make at least [three people](http://www.getwox.com/plugin/87#comment-3279728442) happy :)

**Comment by Shinao** [comment]
Oh my ! I though you guys were talking about the search function.
Indeed it should save the value as is and search for it in case-insensitive and not put it in the database in lower case.

**Fixed it. Pushing v1.0.1 to Wox.**

Thanks for the feedback.
